name: GoFmt

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'

      - name: Create Fake Embed Files
        run: |
          touch LiveSplit.AutoSplitters.xml
          touch silksong_autosplit_wasm_stable.wasm
          mkdir -p static
          touch static/axios.min.js
          touch static/index.css
          touch static/css-vars.css
          touch static/index.full.min.js
          touch static/index.iife.min.js
          touch static/vue.global.prod.js

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Set Go Env
        run: |
          go env -w GOOS=windows
          go env -w GOARCH=amd64

      - name: Run goimports
        run: goimports -w .

      - name: Run gofmt
        run: gofmt -s -l -w .

      - name: Build
        run: go build -v ./...

      - name: Submit if there are changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "goimports && gofmt"
          file_pattern: 'go.mod go.sum *.go **/*.go'